export const projects = [
  {
    id: 1,
    slug: 'projeto-01',
    title: 'Nome do Projeto 01',
    image: '/img/arquitetura/01_Estúdio_A/render_04.png',
    thumbnail: '/img/arquitetura/01_Estúdio_A/render_04.png',
    category: 'equipamento público',
    location: 'são paulo - sp',
    year: 2024,
    status: 'construído',
    description: 'Descrição detalhada do projeto 01.',
    content: 'Conteúdo completo sobre o projeto...',
  },
  {
    id: 2,
    slug: 'projeto-02',
    title: 'Nome do Projeto 02',
    image: '/img/objetos/projeto-02.jpg',
    thumbnail: '/img/objetos/projeto-02.jpg',
    category: 'habitação',
    location: 'campinas - sp',
    year: 2023,
    status: 'concluído',
    description: 'Descrição detalhada do projeto 02.',
    content: 'Conteúdo completo sobre o projeto...',
  },
  {
    id: 3,
    slug: 'projeto-03',
    title: 'Nome do Projeto 03',
    image: '/img/objetos/projeto-03.jpg',
    thumbnail: '/img/objetos/projeto-03.jpg',
    category: 'serviços',
    location: 'belo horizonte - mg',
    year: 2022,
    status: 'projeto',
    description: 'Descrição detalhada do projeto 03.',
    content: 'Conteúdo completo sobre o projeto...',
  },
  {
    id: 4,
    slug: 'projeto-04',
    title: 'Nome do Projeto 04',
    image: '/img/objetos/projeto-04.jpg',
    thumbnail: '/img/objetos/projeto-04.jpg',
    category: 'projeto urbano',
    location: 'brasília - df',
    year: 2024,
    status: 'em desenvolvimento',
    description: 'Descrição detalhada do projeto 04.',
    content: 'Conteúdo completo sobre o projeto...',
  },
  {
    id: 5,
    slug: 'projeto-05',
    title: 'Nome do Projeto 05',
    image: '/img/objetos/projeto-05.jpg',
    thumbnail: '/img/objetos/projeto-05.jpg',
    category: 'habitação',
    location: 'são paulo - sp',
    year: 2023,
    status: 'construído',
    description: 'Descrição detalhada do projeto 05.',
    content: 'Conteúdo completo sobre o projeto...',
  },
  {
    id: 6,
    slug: 'projeto-06',
    title: 'Nome do Projeto 06',
    image: '/img/objetos/projeto-06.jpg',
    thumbnail: '/img/objetos/projeto-06.jpg',
    category: 'equipamento público',
    location: 'rio de janeiro - rj',
    year: 2021,
    status: 'concluído',
    description: 'Descrição detalhada do projeto 06.',
    content: 'Conteúdo completo sobre o projeto...',
  },
  {
    id: 7,
    slug: 'projeto-07',
    title: 'Nome do Projeto 07',
    image: '/img/objetos/projeto-07.jpg',
    thumbnail: '/img/objetos/projeto-07.jpg',
    category: 'infra-estrutura',
    location: 'curitiba - pr',
    year: 2022,
    status: 'projeto',
    description: 'Descrição detalhada do projeto 07.',
    content: 'Conteúdo completo sobre o projeto...',
  },
  {
    id: 8,
    slug: 'projeto-08',
    title: 'Nome do Projeto 08',
    image: '/img/objetos/projeto-08.jpg',
    thumbnail: '/img/objetos/projeto-08.jpg',
    category: 'intervenção urbana',
    location: 'salvador - ba',
    year: 2024,
    status: 'em obra',
    description: 'Descrição detalhada do projeto 08.',
    content: 'Conteúdo completo sobre o projeto...',
  },
  {
    id: 9,
    slug: 'projeto-09',
    title: 'Nome do Projeto 09',
    image: '/img/objetos/projeto-09.jpg',
    thumbnail: '/img/objetos/projeto-09.jpg',
    category: 'habitação',
    location: 'recife - pe',
    year: 2023,
    status: 'concluído',
    description: 'Descrição detalhada do projeto 09.',
    content: 'Conteúdo completo sobre o projeto...',
  },
  {
    id: 10,
    slug: 'projeto-10',
    title: 'Nome do Projeto 10',
    image: '/img/objetos/projeto-10.jpg',
    thumbnail: '/img/objetos/projeto-10.jpg',
    category: 'serviços',
    location: 'manaus - am',
    year: 2021,
    status: 'projeto',
    description: 'Descrição detalhada do projeto 10.',
    content: 'Conteúdo completo sobre o projeto...',
  },
  {
    id: 11,
    slug: 'projeto-11',
    title: 'Nome do Projeto 11',
    image: '/img/objetos/projeto-11.jpg',
    thumbnail: '/img/objetos/projeto-11.jpg',
    category: 'equipamento público',
    location: 'fortaleza - ce',
    year: 2022,
    status: 'construído',
    description: 'Descrição detalhada do projeto 11.',
    content: 'Conteúdo completo sobre o projeto...',
  },
  {
    id: 12,
    slug: 'projeto-12',
    title: 'Nome do Projeto 12',
    image: '/img/objetos/projeto-12.jpg',
    thumbnail: '/img/objetos/projeto-12.jpg',
    category: 'projeto urbano',
    location: 'belém - pa',
    year: 2024,
    status: 'em desenvolvimento',
    description: 'Descrição detalhada do projeto 12.',
    content: 'Conteúdo completo sobre o projeto...',
  },
  {
    id: 13,
    slug: 'projeto-13',
    title: 'Nome do Projeto 13',
    image: '/img/objetos/projeto-13.jpg',
    thumbnail: '/img/objetos/projeto-13.jpg',
    category: 'habitação',
    location: 'goiânia - go',
    year: 2023,
    status: 'concluído',
    description: 'Descrição detalhada do projeto 13.',
    content: 'Conteúdo completo sobre o projeto...',
  },
  {
    id: 14,
    slug: 'projeto-14',
    title: 'Nome do Projeto 14',
    image: '/img/objetos/projeto-14.jpg',
    thumbnail: '/img/objetos/projeto-14.jpg',
    category: 'infra-estrutura',
    location: 'maceió - al',
    year: 2021,
    status: 'projeto',
    description: 'Descrição detalhada do projeto 14.',
    content: 'Conteúdo completo sobre o projeto...',
  },
  {
    id: 15,
    slug: 'projeto-15',
    title: 'Nome do Projeto 15',
    image: '/img/objetos/projeto-15.jpg',
    thumbnail: '/img/objetos/projeto-15.jpg',
    category: 'intervenção urbana',
    location: 'joão pessoa - pb',
    year: 2022,
    status: 'em obra',
    description: 'Descrição detalhada do projeto 15.',
    content: 'Conteúdo completo sobre o projeto...',
  },
  {
    id: 16,
    slug: 'projeto-16',
    title: 'Nome do Projeto 16',
    image: '/img/objetos/projeto-16.jpg',
    thumbnail: '/img/objetos/projeto-16.jpg',
    category: 'serviços',
    location: 'natalência - rn',
    year: 2024,
    status: 'construído',
    description: 'Descrição detalhada do projeto 16.',
    content: 'Conteúdo completo sobre o projeto...',
  },
]

// Extrair categorias, localizações e anos únicos automaticamente
export const getCategories = () => [...new Set(projects.map(p => p.category))]
export const getLocations = () => [...new Set(projects.map(p => p.location))]
export const getYears = () => [...new Set(projects.map(p => p.year))].sort((a, b) => b - a)
export const getStatus = () => [...new Set(projects.map(p => p.status))]

// Buscar projeto por slug
export const getProjectBySlug = (slug) => projects.find(p => p.slug === slug)